# Keep this file source-only so clang-tidy can scope manifest changes safely.
target_sources(
    simple_platformer_core
    PRIVATE
    ${PROJECT_SOURCE_DIR}/src/actor/actor_id.cpp
    ${PROJECT_SOURCE_DIR}/src/actor/actor_system.cpp
    ${PROJECT_SOURCE_DIR}/src/actor/actor_validation.cpp
    ${PROJECT_SOURCE_DIR}/src/actor/lifecycle.cpp
    ${PROJECT_SOURCE_DIR}/src/combat/attack_system.cpp
    ${PROJECT_SOURCE_DIR}/src/combat/combat.cpp
    ${PROJECT_SOURCE_DIR}/src/combat/projectile_system.cpp
    ${PROJECT_SOURCE_DIR}/src/input/input_state.cpp
    ${PROJECT_SOURCE_DIR}/src/input/input_program.cpp
    ${PROJECT_SOURCE_DIR}/src/inventory/inventory.cpp
    ${PROJECT_SOURCE_DIR}/src/inventory/item.cpp
    ${PROJECT_SOURCE_DIR}/src/inventory/item_use.cpp
    ${PROJECT_SOURCE_DIR}/src/math/aabb.cpp
    ${PROJECT_SOURCE_DIR}/src/math/coordinates.cpp
    ${PROJECT_SOURCE_DIR}/src/math/validation.cpp
    ${PROJECT_SOURCE_DIR}/src/movement/flying_movement.cpp
    ${PROJECT_SOURCE_DIR}/src/movement/platformer_movement.cpp
    ${PROJECT_SOURCE_DIR}/src/movement/surface_climb.cpp
    ${PROJECT_SOURCE_DIR}/src/navigation/actor_navigation.cpp
    ${PROJECT_SOURCE_DIR}/src/navigation/navigation_fill.cpp
    ${PROJECT_SOURCE_DIR}/src/navigation/path_follower.cpp
    ${PROJECT_SOURCE_DIR}/src/navigation/platformer_cells.cpp
    ${PROJECT_SOURCE_DIR}/src/navigation/platformer_connection_cache.cpp
    ${PROJECT_SOURCE_DIR}/src/navigation/platformer_connections.cpp
    ${PROJECT_SOURCE_DIR}/src/navigation/route_search.cpp
    ${PROJECT_SOURCE_DIR}/src/npc/npc_activities.cpp
    ${PROJECT_SOURCE_DIR}/src/npc/npc_scripted_activity.cpp
    ${PROJECT_SOURCE_DIR}/src/npc/npc_senses.cpp
    ${PROJECT_SOURCE_DIR}/src/npc/npc_system.cpp
    ${PROJECT_SOURCE_DIR}/src/npc/npc_fact_rows.cpp
    ${PROJECT_SOURCE_DIR}/src/npc/npc_facts.cpp
    ${PROJECT_SOURCE_DIR}/src/npc/npc_navigation.cpp
    ${PROJECT_SOURCE_DIR}/src/npc/npc_state_machine.cpp
    ${PROJECT_SOURCE_DIR}/src/npc/npc_transitions.cpp
    ${PROJECT_SOURCE_DIR}/src/physics/body.cpp
    ${PROJECT_SOURCE_DIR}/src/physics/collision.cpp
    ${PROJECT_SOURCE_DIR}/src/physics/segment_cast.cpp
    ${PROJECT_SOURCE_DIR}/src/render/actor_sprite.cpp
    ${PROJECT_SOURCE_DIR}/src/render/animation.cpp
    ${PROJECT_SOURCE_DIR}/src/render/animation_system.cpp
    ${PROJECT_SOURCE_DIR}/src/render/cover_fade.cpp
    ${PROJECT_SOURCE_DIR}/src/render/presentation.cpp
    ${PROJECT_SOURCE_DIR}/src/render/camera.cpp
    ${PROJECT_SOURCE_DIR}/src/render/render_scene.cpp
    ${PROJECT_SOURCE_DIR}/src/render/sprite.cpp
    ${PROJECT_SOURCE_DIR}/src/timing/fixed_step.cpp
    ${PROJECT_SOURCE_DIR}/src/timing/frame_profile.cpp
    ${PROJECT_SOURCE_DIR}/src/timing/stopwatch.cpp
    ${PROJECT_SOURCE_DIR}/src/world/tile_map.cpp
    ${PROJECT_SOURCE_DIR}/src/world/world.cpp
    ${PROJECT_SOURCE_DIR}/src/world/level_exit.cpp
    ${PROJECT_SOURCE_DIR}/src/world/level_validation.cpp
    ${PROJECT_SOURCE_DIR}/src/world/pickup.cpp
    ${PROJECT_SOURCE_DIR}/src/world/sight.cpp
    ${PROJECT_SOURCE_DIR}/src/world/world_requests.cpp
    ${PROJECT_SOURCE_DIR}/src/world/world_simulation.cpp
)
